# Generated by Django 3.2.5 on 2021-08-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('personName', models.CharField(max_length=100)),
                ('jobTitle', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('linkedIn', models.URLField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('personalProfile', models.TextField()),
                ('company1', models.CharField(max_length=100)),
                ('role1', models.CharField(max_length=100)),
                ('compan1startdate', models.CharField(max_length=50)),
                ('company1enddate', models.CharField(max_length=50)),
                ('jobDescription1', models.TextField(max_length=200)),
                ('company2', models.CharField(max_length=100)),
                ('role2', models.CharField(max_length=100)),
                ('company2startdate', models.CharField(max_length=50)),
                ('company2enddate', models.CharField(max_length=50)),
                ('jobDescription2', models.TextField(max_length=200)),
                ('skill1', models.CharField(max_length=50)),
                ('skill2', models.CharField(max_length=50)),
                ('skill3', models.CharField(max_length=50)),
                ('skill4', models.CharField(max_length=50)),
                ('skill5', models.CharField(max_length=50)),
                ('skill6', models.CharField(max_length=50)),
                ('collegeName1', models.CharField(max_length=100)),
                ('degree1', models.CharField(max_length=100)),
                ('college1startdate', models.CharField(max_length=50)),
                ('college1enddate', models.CharField(max_length=50)),
                ('cgpa1', models.FloatField()),
                ('collegeName2', models.CharField(max_length=100)),
                ('degree2', models.CharField(max_length=100)),
                ('college2startdate', models.CharField(max_length=50)),
                ('college2enddate', models.CharField(max_length=50)),
                ('cgpa2', models.FloatField()),
                ('project1', models.CharField(max_length=100)),
                ('projectDescription1', models.TextField()),
                ('project2', models.CharField(max_length=100)),
                ('projectDescription2', models.TextField()),
            ],
        ),
    ]
