# Generated by Django 3.2.5 on 2021-08-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='compan1startdate',
            new_name='company1startdate',
        ),
    ]
